# Site settings
name: Ross' Blog
title: Ross' Blog title
email: rrosen326@gmail.com
description: "Ross Rosen startups, web development, Stanford, Seattle"
baseurl: ""
url: "http://rossrosen.me"

# These two came from a previous version of Jekyll.
# highlighter: pygments
# theme: "/smartTheme/theme/assets"


blog_full_posts_before_list: 2

# Build settings
markdown: kramdown
permalinks: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "bizblog"
    values:
      layout: "post"
      aboutText: "This blog focuses on random business things I've felt like sharing. It's mostly an archive (but there is some good stuff is in here, if I do say so myself)."
  - scope:
      path: "devblog"
    values:
      layout: "post"
      aboutText: "This blog focuses technical knowledge I'd like to share."
