# Site settings
name: Ross' Blog
title: Ross' Blog title
email: rrosen326@gmail.com
description: "Blog for Ross Rosen"
baseurl: "k2company.com"
url: "http://k2company.com"
highlighter: pygments

# Build settings
markdown: kramdown
permalinks: pretty
